input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][index]" => "invoice-system-%{service}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index]" => "invoice-system-general" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "invoice-system-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
